import type { ComputationExample } from "@/lib/graph-types";

export const COMPUTATION_EXAMPLES: ComputationExample[] = [
  {
    id: "mul-after-add",
    title: "Multiply after add",
    description:
      String.raw`A classic example:$$f(x,y,z) = (x+y)*z$$ Run backprop and see the gradients on the edges.`,
    nodes: [
      { id: "x", kind: "input", label: "x", value: -2, position: { x: 0, y: 0 } },
      { id: "y", kind: "input", label: "y", value: 5, position: { x: 0, y: 100 } },
      { id: "z", kind: "input", label: "z", value: -4, position: { x: 0, y: 220 } },
      { id: "q", kind: "operation", label: "", op: "add", position: { x: 180, y: 50 } },
      { id: "f", kind: "operation", label: "", op: "mul", position: { x: 340, y: 130 } },
      { id: "out", kind: "output", label: "\\text{out}", position: { x: 500, y: 130 } },
    ],
    edges: [
      { id: "x-q", source: "x", target: "q", targetHandle: "a" },
      { id: "y-q", source: "y", target: "q", targetHandle: "b" },
      { id: "q-f", source: "q", target: "f", targetHandle: "a" },
      { id: "z-f", source: "z", target: "f", targetHandle: "b" },
      { id: "f-out", source: "f", target: "out", targetHandle: "in" },
    ],
  },
  {
    id: "relu-chain",
    title: "Manual Sigmoid",
    description:
      String.raw`A neuron with two inputs, broken down into primitive operations. Here we implement the sigmoid activation manually: $$f(w,x) = \frac{1}{1 + e^{-(w_0x_0 + w_1x_1 + w_2)}}$$`,
    nodes: [
      { id: "w0", kind: "input", label: "w_0", value: 2.00, position: { x: 0, y: 0 } },
      { id: "x0", kind: "input", label: "x_0", value: -1.00, position: { x: 0, y: 80 } },
      { id: "w1", kind: "input", label: "w_1", value: -3.00, position: { x: 0, y: 160 } },
      { id: "x1", kind: "input", label: "x_1", value: -2.00, position: { x: 0, y: 240 } },
      { id: "w2", kind: "input", label: "w_2", value: -3.00, position: { x: 0, y: 320 } },
      { id: "mul1", kind: "operation", label: "", op: "mul", position: { x: 150, y: 40 } },
      { id: "mul2", kind: "operation", label: "", op: "mul", position: { x: 150, y: 200 } },
      { id: "add1", kind: "operation", label: "", op: "add", position: { x: 300, y: 120 } },
      { id: "add2", kind: "operation", label: "", op: "add", position: { x: 450, y: 220 } },
      { id: "neg_c", kind: "input", label: "-1", value: -1.00, position: { x: 475, y: 320 } },
      { id: "neg", kind: "operation", label: "", op: "mul", position: { x: 600, y: 228 } },
      { id: "exp", kind: "operation", label: "", op: "exp", position: { x: 752, y: 228 } },
      { id: "c", kind: "input", label: "1", value: 1.00, position: { x: 762, y: 320 } },
      { id: "add3", kind: "operation", label: "", op: "add", position: { x: 901, y: 235 } },
      { id: "pow", kind: "operation", label: "", op: "pow", parameter: -1, position: { x: 1050, y: 236 } },
      { id: "out", kind: "output", label: "\\text{out}", position: { x: 1201, y: 236 } },
    ],
    edges: [
      { id: "w0-mul1", source: "w0", target: "mul1", targetHandle: "a" },
      { id: "x0-mul1", source: "x0", target: "mul1", targetHandle: "b" },
      { id: "w1-mul2", source: "w1", target: "mul2", targetHandle: "a" },
      { id: "x1-mul2", source: "x1", target: "mul2", targetHandle: "b" },
      { id: "mul1-add1", source: "mul1", target: "add1", targetHandle: "a" },
      { id: "mul2-add1", source: "mul2", target: "add1", targetHandle: "b" },
      { id: "add1-add2", source: "add1", target: "add2", targetHandle: "a" },
      { id: "w2-add2", source: "w2", target: "add2", targetHandle: "b" },
      { id: "add2-neg", source: "add2", target: "neg", targetHandle: "a" },
      { id: "neg_c-neg", source: "neg_c", target: "neg", targetHandle: "b" },
      { id: "neg-exp", source: "neg", target: "exp", targetHandle: "a" },
      { id: "exp-add3", source: "exp", target: "add3", targetHandle: "a" },
      { id: "c-add3", source: "c", target: "add3", targetHandle: "b" },
      { id: "add3-pow", source: "add3", target: "pow", targetHandle: "a" },
      { id: "pow-out", source: "pow", target: "out", targetHandle: "in" },
    ],
  },
  {
    id: "max-multiply",
    title: "Max and Multiply",
    description:
      String.raw`A slightly more complex computation graph with a max operation: $$f(x,y,z,w) = (x * y + \max(z, w)) * 2$$`,
    nodes: [
      { id: "x", kind: "input", label: "x", value: 3.00, position: { x: 0, y: 0 } },
      { id: "y", kind: "input", label: "y", value: -4.00, position: { x: 0, y: 100 } },
      { id: "z", kind: "input", label: "z", value: 2.00, position: { x: 0, y: 220 } },
      { id: "w", kind: "input", label: "w", value: -1.00, position: { x: 0, y: 320 } },
      { id: "mul1", kind: "operation", label: "", op: "mul", position: { x: 180, y: 50 } },
      { id: "max1", kind: "operation", label: "", op: "max", position: { x: 180, y: 270 } },
      { id: "add1", kind: "operation", label: "", op: "add", position: { x: 340, y: 160 } },
      { id: "c2", kind: "input", label: "2", value: 2.00, position: { x: 340, y: 260 } },
      { id: "mul2", kind: "operation", label: "", op: "mul", position: { x: 500, y: 167.55029585798815 } },
      { id: "out", kind: "output", label: "\\text{out}", position: { x: 648.3313609467456, y: 168.23668639053253 } },
    ],
    edges: [
      { id: "x-mul1", source: "x", target: "mul1", targetHandle: "a" },
      { id: "y-mul1", source: "y", target: "mul1", targetHandle: "b" },
      { id: "z-max1", source: "z", target: "max1", targetHandle: "a" },
      { id: "w-max1", source: "w", target: "max1", targetHandle: "b" },
      { id: "mul1-add1", source: "mul1", target: "add1", targetHandle: "a" },
      { id: "max1-add1", source: "max1", target: "add1", targetHandle: "b" },
      { id: "add1-mul2", source: "add1", target: "mul2", targetHandle: "a" },
      { id: "c2-mul2", source: "c2", target: "mul2", targetHandle: "b" },
      { id: "mul2-out", source: "mul2", target: "out", targetHandle: "in" },
    ],
  },
];
