import type { PracticeExample } from "@/lib/graph-types";

export const PRACTICE_EXAMPLES: PracticeExample[] = [
  {
    id: "mul-after-add",
    title: "Multiply after add",
    description:
      String.raw`A classic micrograd example:$f(x,y,z) = (x+y)z$. Run backprop and compare the gradients to the diagram.`,
    nodes: [
      { id: "x", kind: "input", label: "x", value: -2, position: { x: 0, y: 0 } },
      { id: "y", kind: "input", label: "y", value: 5, position: { x: 0, y: 100 } },
      { id: "z", kind: "input", label: "z", value: -4, position: { x: 0, y: 220 } },
      { id: "q", kind: "operation", label: "", op: "add", position: { x: 180, y: 50 } },
      { id: "f", kind: "operation", label: "", op: "mul", position: { x: 340, y: 130 } },
      { id: "out", kind: "output", label: "\\text{out}", position: { x: 500, y: 130 } },
    ],
    edges: [
      { id: "x-q", source: "x", target: "q", targetHandle: "a" },
      { id: "y-q", source: "y", target: "q", targetHandle: "b" },
      { id: "q-f", source: "q", target: "f", targetHandle: "a" },
      { id: "z-f", source: "z", target: "f", targetHandle: "b" },
      { id: "f-out", source: "f", target: "out", targetHandle: "in" },
    ],
  },
  {
    id: "relu-chain",
    title: "Manual Sigmoid",
    description:
      String.raw`A neuron with two inputs, broken down into primitive operations. Here we implement the sigmoid activation manually: $f(w,x) = \frac{1}{1 + e^{-(w_0x_0 + w_1x_1 + w_2)}}$.`,
    nodes: [
      { id: "w0", kind: "input", label: "w_0", value: 2.00, position: { x: 0, y: 0 } },
      { id: "x0", kind: "input", label: "x_0", value: -1.00, position: { x: 0, y: 80 } },
      { id: "w1", kind: "input", label: "w_1", value: -3.00, position: { x: 0, y: 160 } },
      { id: "x1", kind: "input", label: "x_1", value: -2.00, position: { x: 0, y: 240 } },
      { id: "w2", kind: "input", label: "w_2", value: -3.00, position: { x: 0, y: 320 } },
      { id: "mul1", kind: "operation", label: "", op: "mul", position: { x: 150, y: 40 } },
      { id: "mul2", kind: "operation", label: "", op: "mul", position: { x: 150, y: 200 } },
      { id: "add1", kind: "operation", label: "", op: "add", position: { x: 300, y: 120 } },
      { id: "add2", kind: "operation", label: "", op: "add", position: { x: 450, y: 220 } },
      { id: "neg_c", kind: "input", label: "-1", value: -1.00, position: { x: 475, y: 320 } },
      { id: "neg", kind: "operation", label: "", op: "mul", position: { x: 600, y: 228 } },
      { id: "exp", kind: "operation", label: "", op: "exp", position: { x: 752, y: 228 } },
      { id: "c", kind: "input", label: "1", value: 1.00, position: { x: 762, y: 320 } },
      { id: "add3", kind: "operation", label: "", op: "add", position: { x: 901, y: 235 } },
      { id: "pow", kind: "operation", label: "", op: "pow", parameter: -1, position: { x: 1050, y: 236 } },
      { id: "out", kind: "output", label: "\text{out}", position: { x: 1201, y: 236 } },
    ],
    edges: [
      { id: "w0-mul1", source: "w0", target: "mul1", targetHandle: "a" },
      { id: "x0-mul1", source: "x0", target: "mul1", targetHandle: "b" },
      { id: "w1-mul2", source: "w1", target: "mul2", targetHandle: "a" },
      { id: "x1-mul2", source: "x1", target: "mul2", targetHandle: "b" },
      { id: "mul1-add1", source: "mul1", target: "add1", targetHandle: "a" },
      { id: "mul2-add1", source: "mul2", target: "add1", targetHandle: "b" },
      { id: "add1-add2", source: "add1", target: "add2", targetHandle: "a" },
      { id: "w2-add2", source: "w2", target: "add2", targetHandle: "b" },
      { id: "add2-neg", source: "add2", target: "neg", targetHandle: "a" },
      { id: "neg_c-neg", source: "neg_c", target: "neg", targetHandle: "b" },
      { id: "neg-exp", source: "neg", target: "exp", targetHandle: "a" },
      { id: "exp-add3", source: "exp", target: "add3", targetHandle: "a" },
      { id: "c-add3", source: "c", target: "add3", targetHandle: "b" },
      { id: "add3-pow", source: "add3", target: "pow", targetHandle: "a" },
      { id: "pow-out", source: "pow", target: "out", targetHandle: "in" },
    ],
  },
  {
    id: "tanh-sigmoid",
    title: "Nonlinear stack",
    description:
      String.raw`Explore chained nonlinearities with $q = \tanh(x + y)$ and $f = \text{sigmoid}(q)$. Small changes here make gradient saturation easy to see.`,
    nodes: [
      { id: "x3", kind: "input", label: "x", value: 1.25, position: { x: 0, y: 20 } },
      { id: "y3", kind: "input", label: "y", value: -0.5, position: { x: 0, y: 130 } },
      { id: "sum3", kind: "operation", label: "", op: "add", position: { x: 180, y: 70 } },
      { id: "tanh3", kind: "operation", label: "", op: "tanh", position: { x: 340, y: 70 } },
      { id: "sig3", kind: "operation", label: "", op: "sigmoid", position: { x: 500, y: 70 } },
      { id: "out3", kind: "output", label: "\\text{out}", position: { x: 660, y: 70 } },
    ],
    edges: [
      { id: "x3-sum3", source: "x3", target: "sum3", targetHandle: "a" },
      { id: "y3-sum3", source: "y3", target: "sum3", targetHandle: "b" },
      { id: "sum3-tanh3", source: "sum3", target: "tanh3", targetHandle: "a" },
      { id: "tanh3-sig3", source: "tanh3", target: "sig3", targetHandle: "a" },
      { id: "sig3-out3", source: "sig3", target: "out3", targetHandle: "in" },
    ],
  },
];
